=== uo294532/SEW_testing/xml/circuito.dtd
<!ELEMENT circuitos (circuito*)>
<!ELEMENT circuito (nombre,longitud_circuito,anchura_media,fecha,hora,vueltas,localidad,país,bibliografía,fotografías,vídeos,coordenadas,tramos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud_circuito (#PCDATA)>
<!ATTLIST longitud_circuito unidades CDATA #REQUIRED>
<!ELEMENT anchura_media (#PCDATA)>
<!ATTLIST anchura_media unidades CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ATTLIST fecha año CDATA #REQUIRED>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT país (#PCDATA)>
<!ELEMENT bibliografía (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT fotografías (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT vídeos (vídeo*)>
<!ELEMENT vídeo (#PCDATA)>
<!ELEMENT coordenadas (longitud,latitud,altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidades CDATA #REQUIRED>
<!ELEMENT tramos (tramo*)>
<!ELEMENT tramo (distancia,coordenadas,sector)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidades CDATA #REQUIRED>
<!ELEMENT sector (#PCDATA)>

=== uo294532/SEW_testing/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuitos SYSTEM "circuito.dtd">
<!-- en temas que necesiten unidades como atributo -->
<!-- origen de coordenadas es el punto central de la pista en la linea de salida-->
 <circuitos>
    <circuito>
        <nombre>Shanghai International Circuit</nombre>
        <longitud_circuito unidades="km">5451</longitud_circuito>
        <anchura_media unidades="m">14</anchura_media>
        <fecha año="2024">21 de abril</fecha>
        <hora>9:00</hora>
        <vueltas>56</vueltas>
        <localidad>Shanghai</localidad>
        <país>China</país>
        <bibliografía>
            <referencia>https://www.formula1.com/en/racing/2024/china/circuit</referencia>
            <referencia>https://www.travelchinaguide.com/attraction/shanghai/international-circuit.htm</referencia>
            <referencia>https://www.formula1.com/en/racing/2024</referencia>
            <referencia>https://www.worldtimebuddy.com/</referencia>
            <referencia>https://www.randymajors.org/elevation-on-google-maps</referencia>
        </bibliografía>
        <fotografías>
            <foto>China_Circuit.png</foto>
            <foto>Shanghai_Hairpin.png</foto>
            <foto>Shanghai_Start.png</foto>
        </fotografías>
        <vídeos>
            <vídeo>Verstappen vs Vettel At The Hairpin - Chinese Grand Prix.mp4</vídeo>    
        </vídeos>
        <coordenadas>
            <longitud>121,221009</longitud>
            <latitud>31,336758</latitud>
            <altitud unidades="m">4,1748493</altitud>
        </coordenadas>
        <!-- 36 tramos aprox-->
        <tramos>
            <tramo>
                <distancia unidades="m">308.91</distancia>
                <coordenadas>
                    <longitud>121.2202777777778</longitud>
                    <latitud>31.33722222222222</latitud>
                    <altitud unidades="m">5.9019566</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>
            
            <tramo>
                <distancia unidades="m">85.47</distancia>
                <coordenadas>
                    <longitud>121.217136880194</longitud>
                    <latitud>31.33661939128587</latitud>
                    <altitud unidades="m">5.5528994</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">14.84</distancia>
                <coordenadas>
                    <longitud>121.2164303983079</longitud>
                    <latitud>31.33688275192819</latitud>
                    <altitud unidades="m">5.0092069</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">1155.83</distancia>
                <coordenadas>
                    <longitud>121.216201492599</longitud>
                    <latitud>31.33761112496245</latitud>
                    <altitud unidades="m">5.0792069</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">97.52</distancia>
                <coordenadas>
                    <longitud>121.2164552936754</longitud>
                    <latitud>31.3379625396121</latitud>
                    <altitud unidades="m">5.2225502</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">84.32</distancia>
                <coordenadas>
                    <longitud>121.2170321380549</longitud>
                    <latitud>31.33802188255702</latitud>
                    <altitud unidades="m">5.3306227</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">47.53</distancia>
                <coordenadas>
                    <longitud>121.2172319621992</longitud>
                    <latitud>31.33780410838789</latitud>
                    <altitud unidades="m">5.8103567</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">56.67</distancia>
                <coordenadas>
                    <longitud>121.2170624304668</longitud>
                    <latitud>31.33737878306495</latitud>
                    <altitud unidades="m">5.8103373</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">60.58</distancia>
                <coordenadas>
                    <longitud>121.2172762527056</longitud>
                    <latitud>31.33711532220504</latitud>
                    <altitud unidades="m">5.8867288</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">55.14</distancia>
                <coordenadas>
                    <longitud>121.217615294655</longitud>
                    <latitud>31.3371752106771</latitud>
                    <altitud unidades="m">5.9267288</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">26.94</distancia>
                <coordenadas>
                    <longitud>121.2179095904569</longitud>
                    <latitud>31.33765995806406</latitud>
                    <altitud unidades="m">5.2965324</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">47.7</distancia>
                <coordenadas>
                    <longitud>121.2177994356075</longitud>
                    <latitud>31.33806532657334</latitud>
                    <altitud unidades="m">5.2489486</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">28.47</distancia>
                <coordenadas>
                    <longitud>121.215755500081</longitud>
                    <latitud>31.34006420714989</latitud>
                    <altitud unidades="m">5.5516580</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">235.78</distancia>
                <coordenadas>
                    <longitud>121.2154895175045</longitud>
                    <latitud>31.34067936931568</latitud>
                    <altitud unidades="m">5.3235697</altitud>
                </coordenadas>
                <sector>1</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">238.36</distancia>
                <coordenadas>
                    <longitud>121.214944664914</longitud>
                    <latitud>31.34208060796633</latitud>
                    <altitud unidades="m">5.8405979</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>
            
            <tramo>
                <distancia unidades="m">85.3</distancia>
                <coordenadas>
                    <longitud>121.2150674846096</longitud>
                    <latitud>31.34223605089332</latitud>
                    <altitud unidades="m">5.1593857</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">37.36</distancia>
                <coordenadas>
                    <longitud>121.2153634010456</longitud>
                    <latitud>31.34215682499574</latitud>
                    <altitud unidades="m">5.5435004</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">99.35</distancia>
                <coordenadas>
                    <longitud>121.2159033183808</longitud>
                    <latitud>31.34176399932302</latitud>
                    <altitud unidades="m">5.7435004</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">57.54</distancia>
                <coordenadas>
                    <longitud>121.2172604129909</longitud>
                    <latitud>31.33987983888281</latitud>
                    <altitud unidades="m">5.4720121</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">50.87</distancia>
                <coordenadas>
                    <longitud>121.2181330019942</longitud>
                    <latitud>31.33950983071703</latitud>
                    <altitud unidades="m">5.8229781</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">55.25</distancia>
                <coordenadas>
                    <longitud>121.2190520911721</longitud>
                    <latitud>31.33974659965385</latitud>
                    <altitud unidades="m">5.9959773</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">99.03</distancia>
                <coordenadas>
                    <longitud>121.2194290206254</longitud>
                    <latitud>31.34010968850032</latitud>
                    <altitud unidades="m">5.3545394</altitud>
                </coordenadas>
                <sector>2</sector>
            </tramo>

            <tramo>
                <distancia unidades="m">55.82</distancia>
                <coordenadas>
